// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>csharp_openapi</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.PartnerWallet.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class WalletExpressCheckoutRequest
    {

        private string merchantCheckoutIdField;

        private string oauthTokenField;

        private string originUrlField;

        private string currencyCodeField;

        private double orderAmountField;

        private int precheckoutTransactionIdField;

        private int consumerWalletIdField;

        private string merchantParameterIdField;

        private int cardIdField;

        private int shippingAddressIdField;

        private int rewardProgramIdField;

        private int walletIdField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MerchantCheckoutId
        {
            get
            {
                return this.merchantCheckoutIdField;
            }
            set
            {
                this.merchantCheckoutIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string OauthToken
        {
            get
            {
                return this.oauthTokenField;
            }
            set
            {
                this.oauthTokenField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string OriginUrl
        {
            get
            {
                return this.originUrlField;
            }
            set
            {
                this.originUrlField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string CurrencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public double OrderAmount
        {
            get
            {
                return this.orderAmountField;
            }
            set
            {
                this.orderAmountField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public int PrecheckoutTransactionId
        {
            get
            {
                return this.precheckoutTransactionIdField;
            }
            set
            {
                this.precheckoutTransactionIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public int ConsumerWalletId
        {
            get
            {
                return this.consumerWalletIdField;
            }
            set
            {
                this.consumerWalletIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string MerchantParameterId
        {
            get
            {
                return this.merchantParameterIdField;
            }
            set
            {
                this.merchantParameterIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public int CardId
        {
            get
            {
                return this.cardIdField;
            }
            set
            {
                this.cardIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public int ShippingAddressId
        {
            get
            {
                return this.shippingAddressIdField;
            }
            set
            {
                this.shippingAddressIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public int RewardProgramId
        {
            get
            {
                return this.rewardProgramIdField;
            }
            set
            {
                this.rewardProgramIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public int WalletId
        {
            get
            {
                return this.walletIdField;
            }
            set
            {
                this.walletIdField = value;
            }
        }
    }
}
