// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>moneysend</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.MoneySend.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class PaymentRequest
    {

        private String localDateField;

        private String localTimeField;

        private long? transactionReferenceField;

        private String senderNameField;

        private PaymentRequestSenderAddress senderAddressField;

        private PaymentRequestReceivingCard receivingCardField;

        private PaymentRequestReceivingMapped receivingMappedField;

        private PaymentRequestReceivingAmount receivingAmountField;

        private String iCAField;

        private long? processorIdField;

        private int? routingAndTransitNumberField;

        private PaymentRequestCardAcceptor cardAcceptorField;

        private String transactionDescField;

        private int? merchantIdField;

        public PaymentRequest()
        {
            this.cardAcceptorField = new PaymentRequestCardAcceptor();
            this.receivingAmountField = new PaymentRequestReceivingAmount();
            this.receivingMappedField = new PaymentRequestReceivingMapped();
            this.receivingCardField = new PaymentRequestReceivingCard();
            this.senderAddressField = new PaymentRequestSenderAddress();
        }

        public String LocalDate
        {
            get
            {
                return this.localDateField;
            }
            set
            {
                this.localDateField = value;
            }
        }

        public String LocalTime
        {
            get
            {
                return this.localTimeField;
            }
            set
            {
                this.localTimeField = value;
            }
        }

        public long? TransactionReference
        {
            get
            {
                return this.transactionReferenceField;
            }
            set
            {
                this.transactionReferenceField = value;
            }
        }

        public String SenderName
        {
            get
            {
                return this.senderNameField;
            }
            set
            {
                this.senderNameField = value;
            }
        }

        public PaymentRequestSenderAddress SenderAddress
        {
            get
            {
                return this.senderAddressField;
            }
            set
            {
                this.senderAddressField = value;
            }
        }

        public PaymentRequestReceivingCard ReceivingCard
        {
            get
            {
                return this.receivingCardField;
            }
            set
            {
                this.receivingCardField = value;
            }
        }

        public PaymentRequestReceivingMapped ReceivingMapped
        {
            get
            {
                return this.receivingMappedField;
            }
            set
            {
                this.receivingMappedField = value;
            }
        }

        public PaymentRequestReceivingAmount ReceivingAmount
        {
            get
            {
                return this.receivingAmountField;
            }
            set
            {
                this.receivingAmountField = value;
            }
        }

        public String ICA
        {
            get
            {
                return this.iCAField;
            }
            set
            {
                this.iCAField = value;
            }
        }

        public long? ProcessorId
        {
            get
            {
                return this.processorIdField;
            }
            set
            {
                this.processorIdField = value;
            }
        }

        public int? RoutingAndTransitNumber
        {
            get
            {
                return this.routingAndTransitNumberField;
            }
            set
            {
                this.routingAndTransitNumberField = value;
            }
        }

        public PaymentRequestCardAcceptor CardAcceptor
        {
            get
            {
                return this.cardAcceptorField;
            }
            set
            {
                this.cardAcceptorField = value;
            }
        }

        public String TransactionDesc
        {
            get
            {
                return this.transactionDescField;
            }
            set
            {
                this.transactionDescField = value;
            }
        }

        public int? MerchantId
        {
            get
            {
                return this.merchantIdField;
            }
            set
            {
                this.merchantIdField = value;
            }
        }
    }

    public partial class PaymentRequestSenderAddress
    {

        private String line1Field;

        private String line2Field;

        private String cityField;

        private String countrySubdivisionField;

        private int? postalCodeField;

        private String countryField;

        public String Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        public String Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        public String City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        public String CountrySubdivision
        {
            get
            {
                return this.countrySubdivisionField;
            }
            set
            {
                this.countrySubdivisionField = value;
            }
        }

        public int? PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        public String Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    public partial class PaymentRequestReceivingCard
    {

        private long? accountNumberField;

        public long? AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
    }

    public partial class PaymentRequestReceivingMapped
    {

        private String subscriberIdField;

        private String subscriberTypeField;

        private String subscriberAliasField;

        public String SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }

        public String SubscriberType
        {
            get
            {
                return this.subscriberTypeField;
            }
            set
            {
                this.subscriberTypeField = value;
            }
        }

        public String SubscriberAlias
        {
            get
            {
                return this.subscriberAliasField;
            }
            set
            {
                this.subscriberAliasField = value;
            }
        }
    }

    public partial class PaymentRequestReceivingAmount
    {

        private int? valueField;

        private int? currencyField;

        public int? Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        public int? Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }

    public partial class PaymentRequestCardAcceptor
    {

        private String nameField;

        private String cityField;

        private String stateField;

        private int? postalCodeField;

        private String countryField;

        public String Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public String City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        public String State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        public int? PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        public String Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }
}
