// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>Match</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.Match.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mastercard.com/termination")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://mastercard.com/termination", IsNullable = false)]
    public partial class TerminationInquiryRequest
    {

        private string acquirerIdField;

        private string transactionReferenceNumberField;

        private merchant_Type merchantField;

        public TerminationInquiryRequest()
        {
            this.merchantField = new merchant_Type();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string AcquirerId
        {
            get
            {
                return this.acquirerIdField;
            }
            set
            {
                this.acquirerIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string TransactionReferenceNumber
        {
            get
            {
                return this.transactionReferenceNumberField;
            }
            set
            {
                this.transactionReferenceNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public merchant_Type Merchant
        {
            get
            {
                return this.merchantField;
            }
            set
            {
                this.merchantField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mastercard.com/termination")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://mastercard.com/termination", IsNullable = true)]
    public partial class merchant_Type
    {

        private string nameField;

        private string doingBusinessAsNameField;

        private string phoneNumberField;

        private address_Type addressField;

        private string countrySubdivisionTaxIdField;

        private string nationalTaxIdField;

        private List<principal_Type> principalField;

        public merchant_Type()
        {
            this.principalField = new List<principal_Type>();
            this.addressField = new address_Type();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string DoingBusinessAsName
        {
            get
            {
                return this.doingBusinessAsNameField;
            }
            set
            {
                this.doingBusinessAsNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public address_Type Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string CountrySubdivisionTaxId
        {
            get
            {
                return this.countrySubdivisionTaxIdField;
            }
            set
            {
                this.countrySubdivisionTaxIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string NationalTaxId
        {
            get
            {
                return this.nationalTaxIdField;
            }
            set
            {
                this.nationalTaxIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Principal", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public List<principal_Type> Principal
        {
            get
            {
                return this.principalField;
            }
            set
            {
                this.principalField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mastercard.com/termination")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://mastercard.com/termination", IsNullable = true)]
    public partial class address_Type
    {

        private string line1Field;

        private string line2Field;

        private string cityField;

        private string countrySubdivisionField;

        private string postalCodeField;

        private string countryField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string CountrySubdivision
        {
            get
            {
                return this.countrySubdivisionField;
            }
            set
            {
                this.countrySubdivisionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "drivers-license_Type", Namespace = "http://mastercard.com/termination")]
    [System.Xml.Serialization.XmlRootAttribute("drivers-license_Type", Namespace = "http://mastercard.com/termination", IsNullable = true)]
    public partial class driverslicense_Type
    {

        private string numberField;

        private string countrySubdivisionField;

        private string countryField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string CountrySubdivision
        {
            get
            {
                return this.countrySubdivisionField;
            }
            set
            {
                this.countrySubdivisionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mastercard.com/termination")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://mastercard.com/termination", IsNullable = true)]
    public partial class principal_Type
    {

        private string firstNameField;

        private string lastNameField;

        private string nationalIdField;

        private string phoneNumberField;

        private address_Type addressField;

        private driverslicense_Type driversLicenseField;

        public principal_Type()
        {
            this.driversLicenseField = new driverslicense_Type();
            this.addressField = new address_Type();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string NationalId
        {
            get
            {
                return this.nationalIdField;
            }
            set
            {
                this.nationalIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public address_Type Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public driverslicense_Type DriversLicense
        {
            get
            {
                return this.driversLicenseField;
            }
            set
            {
                this.driversLicenseField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://mastercard.com/termination")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://mastercard.com/termination", IsNullable = false)]
    public partial class TerminationInquiry
    {

        private string pageOffsetField;

        private string totalLengthField;

        private string refField;

        private string transactionReferenceNumberField;

        private List<terminatedmerchant_Type> terminatedMerchantField;

        public TerminationInquiry()
        {
            this.terminatedMerchantField = new List<terminatedmerchant_Type>();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 0)]
        public string PageOffset
        {
            get
            {
                return this.pageOffsetField;
            }
            set
            {
                this.pageOffsetField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 1)]
        public string TotalLength
        {
            get
            {
                return this.totalLengthField;
            }
            set
            {
                this.totalLengthField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string TransactionReferenceNumber
        {
            get
            {
                return this.transactionReferenceNumberField;
            }
            set
            {
                this.transactionReferenceNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TerminatedMerchant", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public List<terminatedmerchant_Type> TerminatedMerchant
        {
            get
            {
                return this.terminatedMerchantField;
            }
            set
            {
                this.terminatedMerchantField = value;
            }
        }

        public string GetReferenceId()
        {
            if (this.Ref == null)
            {
                return "";
            }
            return this.Ref.Substring(this.Ref.LastIndexOf('/') + 1);
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "terminated-merchant_Type", Namespace = "http://mastercard.com/termination")]
    [System.Xml.Serialization.XmlRootAttribute("terminated-merchant_Type", Namespace = "http://mastercard.com/termination", IsNullable = true)]
    public partial class terminatedmerchant_Type
    {

        private string terminationReasonCodeField;

        private merchant_Type merchantField;

        private merchantmatch_Type merchantMatchField;

        public terminatedmerchant_Type()
        {
            this.merchantMatchField = new merchantmatch_Type();
            this.merchantField = new merchant_Type();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string TerminationReasonCode
        {
            get
            {
                return this.terminationReasonCodeField;
            }
            set
            {
                this.terminationReasonCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public merchant_Type Merchant
        {
            get
            {
                return this.merchantField;
            }
            set
            {
                this.merchantField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public merchantmatch_Type MerchantMatch
        {
            get
            {
                return this.merchantMatchField;
            }
            set
            {
                this.merchantMatchField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "merchant-match_Type", Namespace = "http://mastercard.com/termination")]
    [System.Xml.Serialization.XmlRootAttribute("merchant-match_Type", Namespace = "http://mastercard.com/termination", IsNullable = true)]
    public partial class merchantmatch_Type
    {

        private matchenumeration_Type nameField;

        private matchenumeration_Type doingBusinessAsNameField;

        private bool doingBusinessAsNameFieldSpecified;

        private matchenumeration_Type phoneNumberField;

        private bool phoneNumberFieldSpecified;

        private matchenumeration_Type addressField;

        private matchenumeration_Type countrySubdivisionTaxIdField;

        private bool countrySubdivisionTaxIdFieldSpecified;

        private matchenumeration_Type nationalTaxIdField;

        private bool nationalTaxIdFieldSpecified;

        private List<principalmatch_Type> principalMatchField;

        public merchantmatch_Type()
        {
            this.principalMatchField = new List<principalmatch_Type>();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public matchenumeration_Type Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public matchenumeration_Type DoingBusinessAsName
        {
            get
            {
                return this.doingBusinessAsNameField;
            }
            set
            {
                this.doingBusinessAsNameField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DoingBusinessAsNameSpecified
        {
            get
            {
                return this.doingBusinessAsNameFieldSpecified;
            }
            set
            {
                this.doingBusinessAsNameFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public matchenumeration_Type PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PhoneNumberSpecified
        {
            get
            {
                return this.phoneNumberFieldSpecified;
            }
            set
            {
                this.phoneNumberFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public matchenumeration_Type Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public matchenumeration_Type CountrySubdivisionTaxId
        {
            get
            {
                return this.countrySubdivisionTaxIdField;
            }
            set
            {
                this.countrySubdivisionTaxIdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountrySubdivisionTaxIdSpecified
        {
            get
            {
                return this.countrySubdivisionTaxIdFieldSpecified;
            }
            set
            {
                this.countrySubdivisionTaxIdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public matchenumeration_Type NationalTaxId
        {
            get
            {
                return this.nationalTaxIdField;
            }
            set
            {
                this.nationalTaxIdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NationalTaxIdSpecified
        {
            get
            {
                return this.nationalTaxIdFieldSpecified;
            }
            set
            {
                this.nationalTaxIdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("PrincipalMatch", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public List<principalmatch_Type> PrincipalMatch
        {
            get
            {
                return this.principalMatchField;
            }
            set
            {
                this.principalMatchField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "match-enumeration_Type", Namespace = "http://mastercard.com/termination")]
    public enum matchenumeration_Type
    {

        /// <remarks/>
        exact,

        /// <remarks/>
        phonetic,

        /// <remarks/>
        none,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "principal-match_Type", Namespace = "http://mastercard.com/termination")]
    [System.Xml.Serialization.XmlRootAttribute("principal-match_Type", Namespace = "http://mastercard.com/termination", IsNullable = true)]
    public partial class principalmatch_Type
    {

        private matchenumeration_Type nameField;

        private matchenumeration_Type nationalIdField;

        private bool nationalIdFieldSpecified;

        private matchenumeration_Type phoneNumberField;

        private bool phoneNumberFieldSpecified;

        private matchenumeration_Type addressField;

        private matchenumeration_Type driversLicenseField;

        private bool driversLicenseFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public matchenumeration_Type Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public matchenumeration_Type NationalId
        {
            get
            {
                return this.nationalIdField;
            }
            set
            {
                this.nationalIdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NationalIdSpecified
        {
            get
            {
                return this.nationalIdFieldSpecified;
            }
            set
            {
                this.nationalIdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public matchenumeration_Type PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PhoneNumberSpecified
        {
            get
            {
                return this.phoneNumberFieldSpecified;
            }
            set
            {
                this.phoneNumberFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public matchenumeration_Type Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public matchenumeration_Type DriversLicense
        {
            get
            {
                return this.driversLicenseField;
            }
            set
            {
                this.driversLicenseField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DriversLicenseSpecified
        {
            get
            {
                return this.driversLicenseFieldSpecified;
            }
            set
            {
                this.driversLicenseFieldSpecified = value;
            }
        }
    }
}
