// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>csharp_mastercardapi</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.PartnerWallet.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AuthorizePairingRequest
    {

        private List<AuthorizePairingRequestPairingDataType> pairingDataTypesField;

        private string oAuthTokenField;

        private string merchantCheckoutIdField;

        private sbyte consumerWalletIdField;

        private string walletIdField;

        private string expressCheckoutField;

        private AuthorizePairingRequestConsumerCountry consumerCountryField;

        public AuthorizePairingRequest()
        {
            this.consumerCountryField = new AuthorizePairingRequestConsumerCountry();
            this.pairingDataTypesField = new List<AuthorizePairingRequestPairingDataType>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PairingDataType", IsNullable = false)]
        public List<AuthorizePairingRequestPairingDataType> PairingDataTypes
        {
            get
            {
                return this.pairingDataTypesField;
            }
            set
            {
                this.pairingDataTypesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string OAuthToken
        {
            get
            {
                return this.oAuthTokenField;
            }
            set
            {
                this.oAuthTokenField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string MerchantCheckoutId
        {
            get
            {
                return this.merchantCheckoutIdField;
            }
            set
            {
                this.merchantCheckoutIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public sbyte ConsumerWalletId
        {
            get
            {
                return this.consumerWalletIdField;
            }
            set
            {
                this.consumerWalletIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string WalletId
        {
            get
            {
                return this.walletIdField;
            }
            set
            {
                this.walletIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string ExpressCheckout
        {
            get
            {
                return this.expressCheckoutField;
            }
            set
            {
                this.expressCheckoutField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public AuthorizePairingRequestConsumerCountry ConsumerCountry
        {
            get
            {
                return this.consumerCountryField;
            }
            set
            {
                this.consumerCountryField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizePairingRequestPairingDataType
    {

        private string typeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizePairingRequestConsumerCountry
    {

        private string codeField;

        private string nameField;

        private sbyte callingCodeField;

        private AuthorizePairingRequestConsumerCountryLocale localeField;

        public AuthorizePairingRequestConsumerCountry()
        {
            this.localeField = new AuthorizePairingRequestConsumerCountryLocale();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public sbyte CallingCode
        {
            get
            {
                return this.callingCodeField;
            }
            set
            {
                this.callingCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public AuthorizePairingRequestConsumerCountryLocale Locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizePairingRequestConsumerCountryLocale
    {

        private string localeField;

        private string languageField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
    }
}
