// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>csharp_mastercardapi</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.PartnerWallet.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AuthorizeCheckoutRequest
    {

        private string oAuthTokenField;

        private AuthorizeCheckoutRequestAuthorizedCheckout authorizedCheckoutField;

        private string preCheckoutTransactionIdField;

        private string deviceTypeField;

        public AuthorizeCheckoutRequest()
        {
            this.authorizedCheckoutField = new AuthorizeCheckoutRequestAuthorizedCheckout();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string OAuthToken
        {
            get
            {
                return this.oAuthTokenField;
            }
            set
            {
                this.oAuthTokenField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public AuthorizeCheckoutRequestAuthorizedCheckout AuthorizedCheckout
        {
            get
            {
                return this.authorizedCheckoutField;
            }
            set
            {
                this.authorizedCheckoutField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string PreCheckoutTransactionId
        {
            get
            {
                return this.preCheckoutTransactionIdField;
            }
            set
            {
                this.preCheckoutTransactionIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string DeviceType
        {
            get
            {
                return this.deviceTypeField;
            }
            set
            {
                this.deviceTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizeCheckoutRequestAuthorizedCheckout
    {

        private AuthorizeCheckoutRequestAuthorizedCheckoutCard cardField;

        private AuthorizeCheckoutRequestAuthorizedCheckoutContact contactField;

        private AuthorizeCheckoutRequestAuthorizedCheckoutShippingAddress shippingAddressField;

        private AuthorizeCheckoutRequestAuthorizedCheckoutAuthenticationOptions authenticationOptionsField;

        private AuthorizeCheckoutRequestAuthorizedCheckoutRewardProgram rewardProgramField;

        public AuthorizeCheckoutRequestAuthorizedCheckout()
        {
            this.rewardProgramField = new AuthorizeCheckoutRequestAuthorizedCheckoutRewardProgram();
            this.authenticationOptionsField = new AuthorizeCheckoutRequestAuthorizedCheckoutAuthenticationOptions();
            this.shippingAddressField = new AuthorizeCheckoutRequestAuthorizedCheckoutShippingAddress();
            this.contactField = new AuthorizeCheckoutRequestAuthorizedCheckoutContact();
            this.cardField = new AuthorizeCheckoutRequestAuthorizedCheckoutCard();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public AuthorizeCheckoutRequestAuthorizedCheckoutCard Card
        {
            get
            {
                return this.cardField;
            }
            set
            {
                this.cardField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public AuthorizeCheckoutRequestAuthorizedCheckoutContact Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public AuthorizeCheckoutRequestAuthorizedCheckoutShippingAddress ShippingAddress
        {
            get
            {
                return this.shippingAddressField;
            }
            set
            {
                this.shippingAddressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public AuthorizeCheckoutRequestAuthorizedCheckoutAuthenticationOptions AuthenticationOptions
        {
            get
            {
                return this.authenticationOptionsField;
            }
            set
            {
                this.authenticationOptionsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public AuthorizeCheckoutRequestAuthorizedCheckoutRewardProgram RewardProgram
        {
            get
            {
                return this.rewardProgramField;
            }
            set
            {
                this.rewardProgramField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizeCheckoutRequestAuthorizedCheckoutCard
    {

        private string brandIdField;

        private string brandNameField;

        private long accountNumberField;

        private AuthorizeCheckoutRequestAuthorizedCheckoutCardBillingAddress billingAddressField;

        private string cardHolderNameField;

        private sbyte expiryMonthField;

        private short expiryYearField;

        public AuthorizeCheckoutRequestAuthorizedCheckoutCard()
        {
            this.billingAddressField = new AuthorizeCheckoutRequestAuthorizedCheckoutCardBillingAddress();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string BrandId
        {
            get
            {
                return this.brandIdField;
            }
            set
            {
                this.brandIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string BrandName
        {
            get
            {
                return this.brandNameField;
            }
            set
            {
                this.brandNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public long AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public AuthorizeCheckoutRequestAuthorizedCheckoutCardBillingAddress BillingAddress
        {
            get
            {
                return this.billingAddressField;
            }
            set
            {
                this.billingAddressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string CardHolderName
        {
            get
            {
                return this.cardHolderNameField;
            }
            set
            {
                this.cardHolderNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public sbyte ExpiryMonth
        {
            get
            {
                return this.expiryMonthField;
            }
            set
            {
                this.expiryMonthField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public short ExpiryYear
        {
            get
            {
                return this.expiryYearField;
            }
            set
            {
                this.expiryYearField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizeCheckoutRequestAuthorizedCheckoutCardBillingAddress
    {

        private string cityField;

        private string countryField;

        private string countrySubdivisionField;

        private string line1Field;

        private string line2Field;

        private string line3Field;

        private short postalCodeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CountrySubdivision
        {
            get
            {
                return this.countrySubdivisionField;
            }
            set
            {
                this.countrySubdivisionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string Line3
        {
            get
            {
                return this.line3Field;
            }
            set
            {
                this.line3Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public short PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizeCheckoutRequestAuthorizedCheckoutContact
    {

        private string firstNameField;

        private string middleNameField;

        private string lastNameField;

        private string genderField;

        private AuthorizeCheckoutRequestAuthorizedCheckoutContactDateOfBirth dateOfBirthField;

        private string countryField;

        private string emailAddressField;

        private long phoneNumberField;

        public AuthorizeCheckoutRequestAuthorizedCheckoutContact()
        {
            this.dateOfBirthField = new AuthorizeCheckoutRequestAuthorizedCheckoutContactDateOfBirth();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public AuthorizeCheckoutRequestAuthorizedCheckoutContactDateOfBirth DateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public long PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizeCheckoutRequestAuthorizedCheckoutContactDateOfBirth
    {

        private short yearField;

        private sbyte monthField;

        private sbyte dayField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public short Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public sbyte Month
        {
            get
            {
                return this.monthField;
            }
            set
            {
                this.monthField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public sbyte Day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizeCheckoutRequestAuthorizedCheckoutShippingAddress
    {

        private string cityField;

        private string countryField;

        private string countrySubdivisionField;

        private string line1Field;

        private string line2Field;

        private string line3Field;

        private int postalCodeField;

        private string recipientNameField;

        private string recipientPhoneNumberField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CountrySubdivision
        {
            get
            {
                return this.countrySubdivisionField;
            }
            set
            {
                this.countrySubdivisionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string Line3
        {
            get
            {
                return this.line3Field;
            }
            set
            {
                this.line3Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public int PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string RecipientName
        {
            get
            {
                return this.recipientNameField;
            }
            set
            {
                this.recipientNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string RecipientPhoneNumber
        {
            get
            {
                return this.recipientPhoneNumberField;
            }
            set
            {
                this.recipientPhoneNumberField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizeCheckoutRequestAuthorizedCheckoutAuthenticationOptions
    {

        private string authenticateMethodField;

        private string cardEnrollmentMethodField;

        private string cAvvField;

        private sbyte eciFlagField;

        private string masterCardAssignedIDField;

        private string paResStatusField;

        private string sCEnrollmentStatusField;

        private string signatureVerificationField;

        private string xidField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string AuthenticateMethod
        {
            get
            {
                return this.authenticateMethodField;
            }
            set
            {
                this.authenticateMethodField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string CardEnrollmentMethod
        {
            get
            {
                return this.cardEnrollmentMethodField;
            }
            set
            {
                this.cardEnrollmentMethodField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CAvv
        {
            get
            {
                return this.cAvvField;
            }
            set
            {
                this.cAvvField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public sbyte EciFlag
        {
            get
            {
                return this.eciFlagField;
            }
            set
            {
                this.eciFlagField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string MasterCardAssignedID
        {
            get
            {
                return this.masterCardAssignedIDField;
            }
            set
            {
                this.masterCardAssignedIDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string PaResStatus
        {
            get
            {
                return this.paResStatusField;
            }
            set
            {
                this.paResStatusField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string SCEnrollmentStatus
        {
            get
            {
                return this.sCEnrollmentStatusField;
            }
            set
            {
                this.sCEnrollmentStatusField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string SignatureVerification
        {
            get
            {
                return this.signatureVerificationField;
            }
            set
            {
                this.signatureVerificationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string Xid
        {
            get
            {
                return this.xidField;
            }
            set
            {
                this.xidField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AuthorizeCheckoutRequestAuthorizedCheckoutRewardProgram
    {

        private int rewardNumberField;

        private string rewardIdField;

        private string rewardNameField;

        private sbyte expiryMonthField;

        private short expiryYearField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int RewardNumber
        {
            get
            {
                return this.rewardNumberField;
            }
            set
            {
                this.rewardNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string RewardId
        {
            get
            {
                return this.rewardIdField;
            }
            set
            {
                this.rewardIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string RewardName
        {
            get
            {
                return this.rewardNameField;
            }
            set
            {
                this.rewardNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public sbyte ExpiryMonth
        {
            get
            {
                return this.expiryMonthField;
            }
            set
            {
                this.expiryMonthField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public short ExpiryYear
        {
            get
            {
                return this.expiryYearField;
            }
            set
            {
                this.expiryYearField = value;
            }
        }
    }
}
