// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>csharp_mastercardapi</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.PartnerWallet.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ConnectionHistory
    {

        private ConnectionHistoryMerchantInfo merchantInfoField;

        public ConnectionHistory()
        {
            this.merchantInfoField = new ConnectionHistoryMerchantInfo();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ConnectionHistoryMerchantInfo MerchantInfo
        {
            get
            {
                return this.merchantInfoField;
            }
            set
            {
                this.merchantInfoField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConnectionHistoryMerchantInfo
    {

        private string nameField;

        private int idField;

        private string typeField;

        private ConnectionHistoryMerchantInfoActivityList activityListField;

        public ConnectionHistoryMerchantInfo()
        {
            this.activityListField = new ConnectionHistoryMerchantInfoActivityList();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public ConnectionHistoryMerchantInfoActivityList ActivityList
        {
            get
            {
                return this.activityListField;
            }
            set
            {
                this.activityListField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConnectionHistoryMerchantInfoActivityList
    {

        private ConnectionHistoryMerchantInfoActivityListActivity activityField;

        public ConnectionHistoryMerchantInfoActivityList()
        {
            this.activityField = new ConnectionHistoryMerchantInfoActivityListActivity();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ConnectionHistoryMerchantInfoActivityListActivity Activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConnectionHistoryMerchantInfoActivityListActivity
    {

        private System.DateTime dateField;

        private string expressCheckoutField;

        private string pairingField;

        private ConnectionHistoryMerchantInfoActivityListActivityPairingDataType pairingDataTypeField;

        private string precheckoutDataTypeField;

        public ConnectionHistoryMerchantInfoActivityListActivity()
        {
            this.pairingDataTypeField = new ConnectionHistoryMerchantInfoActivityListActivityPairingDataType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ExpressCheckout
        {
            get
            {
                return this.expressCheckoutField;
            }
            set
            {
                this.expressCheckoutField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Pairing
        {
            get
            {
                return this.pairingField;
            }
            set
            {
                this.pairingField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public ConnectionHistoryMerchantInfoActivityListActivityPairingDataType PairingDataType
        {
            get
            {
                return this.pairingDataTypeField;
            }
            set
            {
                this.pairingDataTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string PrecheckoutDataType
        {
            get
            {
                return this.precheckoutDataTypeField;
            }
            set
            {
                this.precheckoutDataTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConnectionHistoryMerchantInfoActivityListActivityPairingDataType
    {

        private string typeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
}
