// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>MasterCard.SDK.Services.PartnerWallet.Domain</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.PartnerWallet.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Merchant
    {

        private string nameField;

        private string merchantTypeField;

        private string productionUrlField;

        private int cardinalMerchantIdField;

        private string authOptionsField;

        private string sandboxUrlField;

        private string merchantCheckoutIdField;

        private MerchantLogo logoField;

        public Merchant()
        {
            this.logoField = new MerchantLogo();
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string MerchantType
        {
            get
            {
                return this.merchantTypeField;
            }
            set
            {
                this.merchantTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string ProductionUrl
        {
            get
            {
                return this.productionUrlField;
            }
            set
            {
                this.productionUrlField = value;
            }
        }

        public int CardinalMerchantId
        {
            get
            {
                return this.cardinalMerchantIdField;
            }
            set
            {
                this.cardinalMerchantIdField = value;
            }
        }

        public string AuthOptions
        {
            get
            {
                return this.authOptionsField;
            }
            set
            {
                this.authOptionsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string SandboxUrl
        {
            get
            {
                return this.sandboxUrlField;
            }
            set
            {
                this.sandboxUrlField = value;
            }
        }

        public string MerchantCheckoutId
        {
            get
            {
                return this.merchantCheckoutIdField;
            }
            set
            {
                this.merchantCheckoutIdField = value;
            }
        }

        public MerchantLogo Logo
        {
            get
            {
                return this.logoField;
            }
            set
            {
                this.logoField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantLogo
    {

        private string refField;

        private string urlField;

        private string alternateTextField;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string Ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }

        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        public string AlternateText
        {
            get
            {
                return this.alternateTextField;
            }
            set
            {
                this.alternateTextField = value;
            }
        }
    }
}
