// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>Location</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.Location.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Merchants
    {

        private string pageOffsetField;

        private string totalCountField;

        private List<MerchantsMerchant> merchantField;

        public Merchants()
        {
            this.merchantField = new List<MerchantsMerchant>();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string PageOffset
        {
            get
            {
                return this.pageOffsetField;
            }
            set
            {
                if (value == null)
                {
                    this.pageOffsetField = "";
                    return;
                }
                this.pageOffsetField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TotalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                if (value == null)
                {
                    this.totalCountField = "";
                    return;
                }
                this.totalCountField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Merchant", Order = 2)]
        public List<MerchantsMerchant> Merchant
        {
            get
            {
                return this.merchantField;
            }
            set
            {
                this.merchantField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchant
    {

        private string idField;

        private string nameField;

        private string websiteUrlField;

        private string phoneNumberField;

        private string categoryField;

        private MerchantsMerchantLocation locationField;

        private MerchantsMerchantAcceptance acceptanceField;

        private MerchantsMerchantFeatures featuresField;

        public MerchantsMerchant()
        {
            this.featuresField = new MerchantsMerchantFeatures();
            this.acceptanceField = new MerchantsMerchantAcceptance();
            this.locationField = new MerchantsMerchantLocation();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if (value == null)
                {
                    this.idField = "";
                    return;
                }
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 2)]
        public string WebsiteUrl
        {
            get
            {
                return this.websiteUrlField;
            }
            set
            {
                this.websiteUrlField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public MerchantsMerchantLocation Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public MerchantsMerchantAcceptance Acceptance
        {
            get
            {
                return this.acceptanceField;
            }
            set
            {
                this.acceptanceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public MerchantsMerchantFeatures Features
        {
            get
            {
                return this.featuresField;
            }
            set
            {
                this.featuresField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchantLocation
    {

        private string nameField;

        private string distanceField;

        private string distanceUnitField;

        private MerchantsMerchantLocationAddress addressField;

        private MerchantsMerchantLocationPoint pointField;

        public MerchantsMerchantLocation()
        {
            this.pointField = new MerchantsMerchantLocationPoint();
            this.addressField = new MerchantsMerchantLocationAddress();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                if (value == null)
                {
                    this.distanceField = "";
                    return;
                }
                this.distanceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string DistanceUnit
        {
            get
            {
                return this.distanceUnitField;
            }
            set
            {
                this.distanceUnitField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public MerchantsMerchantLocationAddress Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public MerchantsMerchantLocationPoint Point
        {
            get
            {
                return this.pointField;
            }
            set
            {
                this.pointField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchantLocationAddress
    {

        private string line1Field;

        private string line2Field;

        private string cityField;

        private string postalCodeField;

        private MerchantsMerchantLocationAddressCountrySubdivision countrySubdivisionField;

        private MerchantsMerchantLocationAddressCountry countryField;

        public MerchantsMerchantLocationAddress()
        {
            this.countryField = new MerchantsMerchantLocationAddressCountry();
            this.countrySubdivisionField = new MerchantsMerchantLocationAddressCountrySubdivision();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public MerchantsMerchantLocationAddressCountrySubdivision CountrySubdivision
        {
            get
            {
                return this.countrySubdivisionField;
            }
            set
            {
                this.countrySubdivisionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public MerchantsMerchantLocationAddressCountry Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchantLocationAddressCountrySubdivision
    {

        private string nameField;

        private string codeField;

        //[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        //[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchantLocationAddressCountry
    {

        private string nameField;

        private string codeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchantLocationPoint
    {

        private string latitudeField;

        private string longitudeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                if (value == null)
                {
                    this.latitudeField = "";
                    return;
                }
                this.latitudeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                if (value == null)
                {
                    this.longitudeField = "";
                    return;
                }
                this.longitudeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchantAcceptance
    {

        private MerchantsMerchantAcceptancePayPass payPassField;

        public MerchantsMerchantAcceptance()
        {
            this.payPassField = new MerchantsMerchantAcceptancePayPass();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MerchantsMerchantAcceptancePayPass PayPass
        {
            get
            {
                return this.payPassField;
            }
            set
            {
                this.payPassField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchantAcceptancePayPass
    {

        private string concessionField;

        private string pharmacyField;

        private string fuelPumpField;

        private string tollBoothField;

        private string driveThruField;

        private string registerField;

        private string ticketingField;

        private string vendingMachineField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Concession
        {
            get
            {
                return this.concessionField;
            }
            set
            {
                this.concessionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Pharmacy
        {
            get
            {
                return this.pharmacyField;
            }
            set
            {
                this.pharmacyField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string FuelPump
        {
            get
            {
                return this.fuelPumpField;
            }
            set
            {
                this.fuelPumpField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string TollBooth
        {
            get
            {
                return this.tollBoothField;
            }
            set
            {
                this.tollBoothField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string DriveThru
        {
            get
            {
                return this.driveThruField;
            }
            set
            {
                this.driveThruField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string Register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string Ticketing
        {
            get
            {
                return this.ticketingField;
            }
            set
            {
                this.ticketingField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string VendingMachine
        {
            get
            {
                return this.vendingMachineField;
            }
            set
            {
                this.vendingMachineField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchantFeatures
    {

        private MerchantsMerchantFeaturesCashBack cashBackField;

        public MerchantsMerchantFeatures()
        {
            this.cashBackField = new MerchantsMerchantFeaturesCashBack();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MerchantsMerchantFeaturesCashBack CashBack
        {
            get
            {
                return this.cashBackField;
            }
            set
            {
                this.cashBackField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MerchantsMerchantFeaturesCashBack
    {

        private string maximumAmountField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MaximumAmount
        {
            get
            {
                return this.maximumAmountField;
            }
            set
            {
                if (value == null)
                {
                    this.maximumAmountField = "";
                    return;
                }
                this.maximumAmountField = value;
            }
        }
    }
}
