// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>mdes</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.MDES.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class searchResponse
    {

        private searchResponsePANDetails pANDetailsField;

        private List<searchResponseDevice> devicesField;

        private searchResponseResponse responseField;

        public searchResponse()
        {
            this.responseField = new searchResponseResponse();
            this.devicesField = new List<searchResponseDevice>();
            this.pANDetailsField = new searchResponsePANDetails();
        }

        public searchResponsePANDetails PANDetails
        {
            get
            {
                return this.pANDetailsField;
            }
            set
            {
                this.pANDetailsField = value;
            }
        }

        //[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Device", IsNullable = false)]
        public List<searchResponseDevice> Devices
        {
            get
            {
                return this.devicesField;
            }
            set
            {
                this.devicesField = value;
            }
        }

        public searchResponseResponse Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }

    public partial class searchResponsePANDetails
    {

        private string expiryDateField;

        private string panField;

        private string issuerPhoneNumberField;

        private string issuerEmailField;

        public string ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }

        public string Pan
        {
            get
            {
                return this.panField;
            }
            set
            {
                this.panField = value;
            }
        }

        public string IssuerPhoneNumber
        {
            get
            {
                return this.issuerPhoneNumberField;
            }
            set
            {
                this.issuerPhoneNumberField = value;
            }
        }

        public string IssuerEmail
        {
            get
            {
                return this.issuerEmailField;
            }
            set
            {
                this.issuerEmailField = value;
            }
        }
    }

    public partial class searchResponseDevice
    {

        private string deviceIdField;

        private string deviceNickNameField;

        private int deviceTypeCodeField;

        private string deviceTypeDescriptionField;

        private string secureElementIdField;

        private string tokenDisplayIdField;

        private string tokenUniqueIdField;

        private string tokenExpiryDateField;

        private string provisionStatusField;

        private string provisionStatusDescriptionField;

        private searchResponseDeviceAuditInfo auditInfoField;

        private List<searchResponseDeviceComment> commentsField;

        private string currentMappingStatusField;

        private string currentMappingStatusDescriptionField;

        private List<searchResponseDeviceMappingStatusHistory> mappingStatusHistorysField;

        private List<searchResponseDeviceStatusHistory> statusHistorysField;

        private string provisionPathField;

        public searchResponseDevice()
        {
            this.statusHistorysField = new List<searchResponseDeviceStatusHistory>();
            this.mappingStatusHistorysField = new List<searchResponseDeviceMappingStatusHistory>();
            this.commentsField = new List<searchResponseDeviceComment>();
            this.auditInfoField = new searchResponseDeviceAuditInfo();
        }

        public string DeviceId
        {
            get
            {
                return this.deviceIdField;
            }
            set
            {
                this.deviceIdField = value;
            }
        }

        public string DeviceNickName
        {
            get
            {
                return this.deviceNickNameField;
            }
            set
            {
                this.deviceNickNameField = value;
            }
        }

        public int DeviceTypeCode
        {
            get
            {
                return this.deviceTypeCodeField;
            }
            set
            {
                this.deviceTypeCodeField = value;
            }
        }

        public string DeviceTypeDescription
        {
            get
            {
                return this.deviceTypeDescriptionField;
            }
            set
            {
                this.deviceTypeDescriptionField = value;
            }
        }

        public string SecureElementId
        {
            get
            {
                return this.secureElementIdField;
            }
            set
            {
                this.secureElementIdField = value;
            }
        }

        public string TokenDisplayId
        {
            get
            {
                return this.tokenDisplayIdField;
            }
            set
            {
                this.tokenDisplayIdField = value;
            }
        }

        public string TokenUniqueId
        {
            get
            {
                return this.tokenUniqueIdField;
            }
            set
            {
                this.tokenUniqueIdField = value;
            }
        }

        public string TokenExpiryDate
        {
            get
            {
                return this.tokenExpiryDateField;
            }
            set
            {
                this.tokenExpiryDateField = value;
            }
        }

        public string ProvisionStatus
        {
            get
            {
                return this.provisionStatusField;
            }
            set
            {
                this.provisionStatusField = value;
            }
        }

        public string ProvisionStatusDescription
        {
            get
            {
                return this.provisionStatusDescriptionField;
            }
            set
            {
                this.provisionStatusDescriptionField = value;
            }
        }

        public searchResponseDeviceAuditInfo AuditInfo
        {
            get
            {
                return this.auditInfoField;
            }
            set
            {
                this.auditInfoField = value;
            }
        }

        //[System.Xml.Serialization.XmlArrayAttribute(Order = 11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Comment", IsNullable = false)]
        public List<searchResponseDeviceComment> Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        public string CurrentMappingStatus
        {
            get
            {
                return this.currentMappingStatusField;
            }
            set
            {
                this.currentMappingStatusField = value;
            }
        }

        public string CurrentMappingStatusDescription
        {
            get
            {
                return this.currentMappingStatusDescriptionField;
            }
            set
            {
                this.currentMappingStatusDescriptionField = value;
            }
        }

        //[System.Xml.Serialization.XmlArrayAttribute(Order = 14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MappingStatusHistory", IsNullable = false)]
        public List<searchResponseDeviceMappingStatusHistory> MappingStatusHistorys
        {
            get
            {
                return this.mappingStatusHistorysField;
            }
            set
            {
                this.mappingStatusHistorysField = value;
            }
        }

        //[System.Xml.Serialization.XmlArrayAttribute(Order = 15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("StatusHistory", IsNullable = false)]
        public List<searchResponseDeviceStatusHistory> StatusHistorys
        {
            get
            {
                return this.statusHistorysField;
            }
            set
            {
                this.statusHistorysField = value;
            }
        }

        public string ProvisionPath
        {
            get
            {
                return this.provisionPathField;
            }
            set
            {
                this.provisionPathField = value;
            }
        }
    }

    public partial class searchResponseDeviceAuditInfo
    {

        private string userIdField;

        private string userNameField;

        private string organizationField;

        private System.DateTime lastModifiedDateField;

        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        public string Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }

        public System.DateTime LastModifiedDate
        {
            get
            {
                return this.lastModifiedDateField;
            }
            set
            {
                this.lastModifiedDateField = value;
            }
        }
    }

    public partial class searchResponseDeviceComment
    {

        private int referenceIdField;

        private string commentTextField;

        private searchResponseDeviceCommentAuditInfo auditInfoField;

        private string devicePanUniqueIdField;

        public searchResponseDeviceComment()
        {
            this.auditInfoField = new searchResponseDeviceCommentAuditInfo();
        }

        public int ReferenceId
        {
            get
            {
                return this.referenceIdField;
            }
            set
            {
                this.referenceIdField = value;
            }
        }

        public string CommentText
        {
            get
            {
                return this.commentTextField;
            }
            set
            {
                this.commentTextField = value;
            }
        }

        public searchResponseDeviceCommentAuditInfo AuditInfo
        {
            get
            {
                return this.auditInfoField;
            }
            set
            {
                this.auditInfoField = value;
            }
        }

        public string DevicePanUniqueId
        {
            get
            {
                return this.devicePanUniqueIdField;
            }
            set
            {
                this.devicePanUniqueIdField = value;
            }
        }
    }

    public partial class searchResponseDeviceCommentAuditInfo
    {

        private string userIdField;

        private string userNameField;

        private string organizationField;

        private System.DateTime lastModifiedDateField;

        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        public string Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }

        public System.DateTime LastModifiedDate
        {
            get
            {
                return this.lastModifiedDateField;
            }
            set
            {
                this.lastModifiedDateField = value;
            }
        }
    }

    public partial class searchResponseDeviceMappingStatusHistory
    {

        private string statusField;

        private string statusDescriptionField;

        private System.DateTime dateField;

        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }

        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    public partial class searchResponseDeviceStatusHistory
    {

        private string statusField;

        private string statusDescriptionField;

        private System.DateTime dateField;

        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }

        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    public partial class searchResponseResponse
    {

        private int responseCodeField;

        private string descriptionField;

        public int ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }

        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
}
