// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>moneysend</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.MoneySend.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class TransferRequest
    {

        private String localDateField;

        private String localTimeField;

        private long? transactionReferenceField;

        private String senderNameField;

        private TransferRequestSenderAddress senderAddressField;

        private TransferRequestFundingCard fundingCardField;

        private TransferRequestFundingMapped fundingMappedField;
        public bool ShouldSerializeFundingMappedField()
        {
            return fundingMappedField != null;
        }

        private String fundingUCAFField;

        private int? fundingMasterCardAssignedIdField;

        private TransferRequestFundingAmount fundingAmountField;

        private String receiverNameField;

        private TransferRequestReceiverAddress receiverAddressField;

        private int? receiverPhoneField;

        private TransferRequestReceivingCard receivingCardField;

        private TransferRequestReceivingAmount receivingAmountField;

        private String channelField;

        private Boolean uCAFSupportField;

        private String iCAField;

        private long? processorIdField;

        private int? routingAndTransitNumberField;

        private TransferRequestCardAcceptor cardAcceptorField;

        private String transactionDescField;

        private int? merchantIdField;

        public TransferRequest()
        {
            this.cardAcceptorField = new TransferRequestCardAcceptor();
            this.receivingAmountField = new TransferRequestReceivingAmount();
            this.receivingCardField = new TransferRequestReceivingCard();
            this.receiverAddressField = new TransferRequestReceiverAddress();
            this.fundingAmountField = new TransferRequestFundingAmount();
            this.fundingMappedField = new TransferRequestFundingMapped();
            this.fundingCardField = new TransferRequestFundingCard();
            this.senderAddressField = new TransferRequestSenderAddress();
        }

        public String LocalDate
        {
            get
            {
                return this.localDateField;
            }
            set
            {
                this.localDateField = value;
            }
        }

        public String LocalTime
        {
            get
            {
                return this.localTimeField;
            }
            set
            {
                this.localTimeField = value;
            }
        }

        public long? TransactionReference
        {
            get
            {
                return this.transactionReferenceField;
            }
            set
            {
                this.transactionReferenceField = value;
            }
        }

        public String SenderName
        {
            get
            {
                return this.senderNameField;
            }
            set
            {
                this.senderNameField = value;
            }
        }

        public TransferRequestSenderAddress SenderAddress
        {
            get
            {
                return this.senderAddressField;
            }
            set
            {
                this.senderAddressField = value;
            }
        }
        public bool ShouldSerializeSenderAddress()
        {
            return SenderAddress != null;
        }

        public TransferRequestFundingCard FundingCard
        {
            get
            {
                return this.fundingCardField;
            }
            set
            {
                this.fundingCardField = value;
            }
        }
        public bool ShouldSerializeFundingCard()
        {
            return FundingCard != null;
        }

        public TransferRequestFundingMapped FundingMapped
        {
            get
            {
                return this.fundingMappedField;
            }
            set
            {
                this.fundingMappedField = value;
            }
        }
        public bool ShouldSerializeFundingMapped()
        {
            return FundingMapped != null;
        }

        public String FundingUCAF
        {
            get
            {
                return this.fundingUCAFField;
            }
            set
            {
                this.fundingUCAFField = value;
            }
        }

        public int? FundingMasterCardAssignedId
        {
            get
            {
                return this.fundingMasterCardAssignedIdField;
            }
            set
            {
                this.fundingMasterCardAssignedIdField = value;
            }
        }

        public TransferRequestFundingAmount FundingAmount
        {
            get
            {
                return this.fundingAmountField;
            }
            set
            {
                this.fundingAmountField = value;
            }
        }

        public String ReceiverName
        {
            get
            {
                return this.receiverNameField;
            }
            set
            {
                this.receiverNameField = value;
            }
        }

        public TransferRequestReceiverAddress ReceiverAddress
        {
            get
            {
                return this.receiverAddressField;
            }
            set
            {
                this.receiverAddressField = value;
            }
        }

        public int? ReceiverPhone
        {
            get
            {
                return this.receiverPhoneField;
            }
            set
            {
                this.receiverPhoneField = value;
            }
        }

        public TransferRequestReceivingCard ReceivingCard
        {
            get
            {
                return this.receivingCardField;
            }
            set
            {
                this.receivingCardField = value;
            }
        }

        public TransferRequestReceivingAmount ReceivingAmount
        {
            get
            {
                return this.receivingAmountField;
            }
            set
            {
                this.receivingAmountField = value;
            }
        }

        public String Channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }

        public Boolean UCAFSupport
        {
            get
            {
                return this.uCAFSupportField;
            }
            set
            {
                this.uCAFSupportField = value;
            }
        }

        public String ICA
        {
            get
            {
                return this.iCAField;
            }
            set
            {
                this.iCAField = value;
            }
        }

        public long? ProcessorId
        {
            get
            {
                return this.processorIdField;
            }
            set
            {
                this.processorIdField = value;
            }
        }

        public int? RoutingAndTransitNumber
        {
            get
            {
                return this.routingAndTransitNumberField;
            }
            set
            {
                this.routingAndTransitNumberField = value;
            }
        }

        public TransferRequestCardAcceptor CardAcceptor
        {
            get
            {
                return this.cardAcceptorField;
            }
            set
            {
                this.cardAcceptorField = value;
            }
        }

        public String TransactionDesc
        {
            get
            {
                return this.transactionDescField;
            }
            set
            {
                this.transactionDescField = value;
            }
        }

        public int? MerchantId
        {
            get
            {
                return this.merchantIdField;
            }
            set
            {
                this.merchantIdField = value;
            }
        }
    }

    public partial class TransferRequestSenderAddress
    {

        private String line1Field;

        private String line2Field;

        private String cityField;

        private String countrySubdivisionField;

        private int? postalCodeField;

        private String countryField;

        public String Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        public String Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        public String City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        public String CountrySubdivision
        {
            get
            {
                return this.countrySubdivisionField;
            }
            set
            {
                this.countrySubdivisionField = value;
            }
        }

        public int? PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        public String Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    public partial class TransferRequestFundingCard
    {

        private long? accountNumberField;

        private int? expiryMonthField;

        private int? expiryYearField;

        public long? AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        public int? ExpiryMonth
        {
            get
            {
                return this.expiryMonthField;
            }
            set
            {
                this.expiryMonthField = value;
            }
        }

        public int? ExpiryYear
        {
            get
            {
                return this.expiryYearField;
            }
            set
            {
                this.expiryYearField = value;
            }
        }
    }

    public partial class TransferRequestFundingMapped
    {

        private String subscriberIdField;

        private String subscriberTypeField;

        private String subscriberAliasField;

        public String SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        public bool ShouldSerializeSubscriberId()
        {
            return SubscriberId != null;
        }

        public String SubscriberType
        {
            get
            {
                return this.subscriberTypeField;
            }
            set
            {
                this.subscriberTypeField = value;
            }
        }
        public bool ShouldSerializeSubscriberType()
        {
            return SubscriberType != null;
        }

        public String SubscriberAlias
        {
            get
            {
                return this.subscriberAliasField;
            }
            set
            {
                this.subscriberAliasField = value;
            }
        }
        public bool ShouldSerializeSubscriberAlias()
        {
            return SubscriberAlias != null;
        }
    }

    public partial class TransferRequestFundingAmount
    {

        private int? valueField;

        private int? currencyField;

        public int? Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        public int? Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }

    public partial class TransferRequestReceiverAddress
    {

        private String line1Field;

        private String line2Field;

        private String cityField;

        private String countrySubdivisionField;

        private int? postalCodeField;

        private String countryField;

        public String Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        public String Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        public String City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        public String CountrySubdivision
        {
            get
            {
                return this.countrySubdivisionField;
            }
            set
            {
                this.countrySubdivisionField = value;
            }
        }

        public int? PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        public String Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    public partial class TransferRequestReceivingCard
    {

        private long? accountNumberField;

        public long? AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
    }

    public partial class TransferRequestReceivingAmount
    {

        private int? valueField;

        private int? currencyField;

        public int? Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        public int? Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }

    public partial class TransferRequestCardAcceptor
    {

        private String nameField;

        private String cityField;

        private String stateField;

        private int? postalCodeField;

        private String countryField;

        public String Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public String City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        public String State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        public int? PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        public String Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }
}
