// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>moneysend</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.MoneySend.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Transfer
    {
        private int? requestIdField;

        private long? transactionReferenceField;

        private List<TransferTransaction> transactionHistoryField;

        public Transfer()
        {
            this.transactionHistoryField = new List<TransferTransaction>();
        }

        [XmlElementAttribute(Order = 1)]
        public int? RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
        [XmlElementAttribute(Order = 2)]
        public long? TransactionReference
        {
            get
            {
                return this.transactionReferenceField;
            }
            set
            {
                this.transactionReferenceField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transaction", IsNullable = false)]
        public List<TransferTransaction> TransactionHistory
        {
            get
            {
                return this.transactionHistoryField;
            }
            set
            {
                this.transactionHistoryField = value;
            }
        }
    }

    public partial class TransferTransaction
    {

        private String typeField;

        private int? systemTraceAuditNumberField;

        private int? networkReferenceNumberField;

        private int? settlementDateField;

        private TransferTransactionResponse responseField;

        private System.DateTime submitDateTimeField;

        public TransferTransaction()
        {
            this.responseField = new TransferTransactionResponse();
        }

        public String Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public int? SystemTraceAuditNumber
        {
            get
            {
                return this.systemTraceAuditNumberField;
            }
            set
            {
                this.systemTraceAuditNumberField = value;
            }
        }

        public int? NetworkReferenceNumber
        {
            get
            {
                return this.networkReferenceNumberField;
            }
            set
            {
                this.networkReferenceNumberField = value;
            }
        }

        public int? SettlementDate
        {
            get
            {
                return this.settlementDateField;
            }
            set
            {
                this.settlementDateField = value;
            }
        }

        public TransferTransactionResponse Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }

        public System.DateTime SubmitDateTime
        {
            get
            {
                return this.submitDateTimeField;
            }
            set
            {
                this.submitDateTimeField = value;
            }
        }
    }

    public partial class TransferTransactionResponse
    {

        private int? codeField;

        private String descriptionField;

        public int? Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        public String Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
}
