// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>mdes</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.MDES.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class systemStatusResponses
    {

        private systemStatusResponsesSystemResponse systemResponseField;

        public systemStatusResponses()
        {
            this.systemResponseField = new systemStatusResponsesSystemResponse();
        }

        public systemStatusResponsesSystemResponse SystemResponse
        {
            get
            {
                return this.systemResponseField;
            }
            set
            {
                this.systemResponseField = value;
            }
        }
    }

    public partial class systemStatusResponsesSystemResponse
    {

        private int contentIdField;

        private string contentHeaderField;

        private string contentTextField;

        private string contentStatusField;

        private int userIdField;

        private System.DateTime lastModifiedDateField;

        public int ContentId
        {
            get
            {
                return this.contentIdField;
            }
            set
            {
                this.contentIdField = value;
            }
        }

        public string ContentHeader
        {
            get
            {
                return this.contentHeaderField;
            }
            set
            {
                this.contentHeaderField = value;
            }
        }

        public string ContentText
        {
            get
            {
                return this.contentTextField;
            }
            set
            {
                this.contentTextField = value;
            }
        }

        public string ContentStatus
        {
            get
            {
                return this.contentStatusField;
            }
            set
            {
                this.contentStatusField = value;
            }
        }

        public int UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        public System.DateTime LastModifiedDate
        {
            get
            {
                return this.lastModifiedDateField;
            }
            set
            {
                this.lastModifiedDateField = value;
            }
        }
    }
}
