// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>FraudScoring</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.FraudScoring.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ScoreLookupRequest
    {

        private ScoreLookupRequestTransactionDetail transactionDetailField;

        public ScoreLookupRequest()
        {
            this.transactionDetailField = new ScoreLookupRequestTransactionDetail();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ScoreLookupRequestTransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ScoreLookupRequestTransactionDetail
    {

        private long customerIdentifierField;

        private long merchantIdentifierField;

        private long accountNumberField;

        private int accountPrefixField;

        private short accountSuffixField;

        private long transactionAmountField;

        private short transactionDateField;

        private string transactionTimeField;

        private string bankNetReferenceNumberField;

        private int stanField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long CustomerIdentifier
        {
            get
            {
                return this.customerIdentifierField;
            }
            set
            {
                this.customerIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public long MerchantIdentifier
        {
            get
            {
                return this.merchantIdentifierField;
            }
            set
            {
                this.merchantIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public long AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public int AccountPrefix
        {
            get
            {
                return this.accountPrefixField;
            }
            set
            {
                this.accountPrefixField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public short AccountSuffix
        {
            get
            {
                return this.accountSuffixField;
            }
            set
            {
                this.accountSuffixField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public long TransactionAmount
        {
            get
            {
                return this.transactionAmountField;
            }
            set
            {
                this.transactionAmountField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public short TransactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string TransactionTime
        {
            get
            {
                return this.transactionTimeField;
            }
            set
            {
                this.transactionTimeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string BankNetReferenceNumber
        {
            get
            {
                return this.bankNetReferenceNumberField;
            }
            set
            {
                this.bankNetReferenceNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public int Stan
        {
            get
            {
                return this.stanField;
            }
            set
            {
                this.stanField = value;
            }
        }
    }
}
