// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>FraudScoring</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterCard.SDK.Services.FraudScoring.Domain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ScoreLookup
    {

        private string customerIdentifierField;

        private string requestTimestampField;

        private ScoreLookupTransactionDetail transactionDetailField;

        private ScoreLookupScoreResponse scoreResponseField;

        public ScoreLookup()
        {
            this.scoreResponseField = new ScoreLookupScoreResponse();
            this.transactionDetailField = new ScoreLookupTransactionDetail();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string CustomerIdentifier
        {
            get
            {
                return this.customerIdentifierField;
            }
            set
            {
                this.customerIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string RequestTimestamp
        {
            get
            {
                return this.requestTimestampField;
            }
            set
            {
                this.requestTimestampField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ScoreLookupTransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public ScoreLookupScoreResponse ScoreResponse
        {
            get
            {
                return this.scoreResponseField;
            }
            set
            {
                this.scoreResponseField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ScoreLookupTransactionDetail
    {

        private long customerIdentifierField;

        private string merchantIdentifierField;

        private long accountNumberField;

        private int accountPrefixField;

        private short accountSuffixField;

        private long transactionAmountField;

        private short transactionDateField;

        private int transactionTimeField;

        private string bankNetReferenceNumberField;

        private int stanField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long CustomerIdentifier
        {
            get
            {
                return this.customerIdentifierField;
            }
            set
            {
                this.customerIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string MerchantIdentifier
        {
            get
            {
                return this.merchantIdentifierField;
            }
            set
            {
                this.merchantIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public long AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public int AccountPrefix
        {
            get
            {
                return this.accountPrefixField;
            }
            set
            {
                this.accountPrefixField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public short AccountSuffix
        {
            get
            {
                return this.accountSuffixField;
            }
            set
            {
                this.accountSuffixField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public long TransactionAmount
        {
            get
            {
                return this.transactionAmountField;
            }
            set
            {
                this.transactionAmountField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public short TransactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public int TransactionTime
        {
            get
            {
                return this.transactionTimeField;
            }
            set
            {
                this.transactionTimeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string BankNetReferenceNumber
        {
            get
            {
                return this.bankNetReferenceNumberField;
            }
            set
            {
                this.bankNetReferenceNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public int Stan
        {
            get
            {
                return this.stanField;
            }
            set
            {
                this.stanField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ScoreLookupScoreResponse
    {

        private short matchIndicatorField;

        private short fraudScoreField;

        private string reasonCodeField;

        private short rulesAdjustedScoreField;

        private string rulesAdjustedReasonCodeField;

        private string rulesAdjustedReasonCodeSecondaryField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public short MatchIndicator
        {
            get
            {
                return this.matchIndicatorField;
            }
            set
            {
                this.matchIndicatorField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public short FraudScore
        {
            get
            {
                return this.fraudScoreField;
            }
            set
            {
                this.fraudScoreField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ReasonCode
        {
            get
            {
                return this.reasonCodeField;
            }
            set
            {
                this.reasonCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public short RulesAdjustedScore
        {
            get
            {
                return this.rulesAdjustedScoreField;
            }
            set
            {
                this.rulesAdjustedScoreField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string RulesAdjustedReasonCode
        {
            get
            {
                return this.rulesAdjustedReasonCodeField;
            }
            set
            {
                this.rulesAdjustedReasonCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string RulesAdjustedReasonCodeSecondary
        {
            get
            {
                return this.rulesAdjustedReasonCodeSecondaryField;
            }
            set
            {
                this.rulesAdjustedReasonCodeSecondaryField = value;
            }
        }
    }
}
